import Head from "next/head"
import { ReactNode } from "react"
import Navbar from "../Navbar"

type LayoutProps = {
    children: ReactNode,
    title: string
}

const Layout = ({children, title}: LayoutProps) => {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            {children}
        </>
    )
}

export default Layout